name: Update documentation

on: push

jobs:
  build:
    name: Update documentation
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Update submodule
        run: git submodule update --init --recursive --remote repositories/${{ github.event.client_payload.repo }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: update docs for ${{ github.event.client_payload.repo }} to ${{github.event.client_payload.ref}}'
          fetch: false
